apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
